"""Invite-code authentication for beta.

Every request to a protected endpoint must include:

    Authorization: Bearer <invite-code>

The server checks the code against `settings.invite_codes`. Codes are a
shared secret per beta tester, generated by the operator (you) and given
to friends one at a time. To revoke a tester, drop their code from the
INVITE_CODES env var and restart the server.

This module exposes a FastAPI dependency `require_invite()` that
endpoints declare via:

    @app.post("/llm/answer", dependencies=[Depends(require_invite)])
    def answer(...): ...

Migration path to real auth (post-beta): swap this dependency for one
that validates JWTs from your auth provider (Auth0, Clerk, custom
service). The endpoint signatures don't change — only the dependency
implementation.
"""

from __future__ import annotations

from fastapi import Depends, Header, HTTPException, status

from magpie_server.settings import settings


def _extract_bearer(authorization: str | None) -> str:
    """Pull the token out of an `Authorization: Bearer <token>` header."""
    if not authorization:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="missing Authorization header",
            headers={"WWW-Authenticate": "Bearer"},
        )
    parts = authorization.split(maxsplit=1)
    if len(parts) != 2 or parts[0].lower() != "bearer":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="malformed Authorization header (expected 'Bearer <token>')",
            headers={"WWW-Authenticate": "Bearer"},
        )
    return parts[1].strip()


def require_invite(
    authorization: str | None = Header(default=None),
) -> str:
    """FastAPI dependency: validate the invite code and return it.

    Returning the code lets endpoints log who-did-what without separate
    plumbing. Don't expose it back to the caller — it stays in server logs.
    """
    valid = settings.valid_invite_codes()

    # No codes configured = open server. Only OK for local dev. Refuse to
    # operate this way against any non-loopback host so a forgotten env var
    # in production doesn't accidentally publish a free LLM proxy.
    if not valid:
        if settings.host not in ("127.0.0.1", "localhost", "::1"):
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="server not configured (no invite codes set)",
            )
        # Local dev: skip auth entirely. The placeholder return value is
        # what gets logged so you can grep for "anon-localhost" requests.
        return "anon-localhost"

    token = _extract_bearer(authorization)
    if token not in valid:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="invalid invite code",
            headers={"WWW-Authenticate": "Bearer"},
        )
    return token
